-------------------------------------------------------------------------------
Test set: org.g4.certificate.aspect.CopyCacertToJavaKeyStoreTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.046 sec <<< FAILURE!
afterCommand(org.g4.certificate.aspect.CopyCacertToJavaKeyStoreTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.g4.certificate.facade.CertLogger.getLogger(CertLogger.java:43)
	at org.g4.certificate.utilities.CertExceptionHandler.<clinit>(CertExceptionHandler.java:13)
	at org.g4.certificate.utilities.FileUtil.createFile(FileUtil.java:83)
	at org.g4.certificate.aspect.CopyCacertsToJavaKeyStore.afterCommand(CopyCacertsToJavaKeyStore.java:23)
	at org.g4.certificate.aspect.CopyCacertToJavaKeyStoreTest.afterCommand(CopyCacertToJavaKeyStoreTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.g4.certificate.exception.CGVRuntimeException: Errors happens when getting what is used to print log between log4j and java logging
	at org.g4.certificate.facade.CertLogger.getLogType(CertLogger.java:89)
	at org.g4.certificate.facade.CertLogger.getLogger(CertLogger.java:43)
	at org.g4.certificate.utilities.CertUtil.<clinit>(CertUtil.java:24)
	... 34 more
Caused by: java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at org.g4.certificate.utilities.PropertiesAnalyzer.getProperties(PropertiesAnalyzer.java:41)
	at org.g4.certificate.facade.CertLogger.getLogType(CertLogger.java:87)
	... 36 more

